# 01 - Dataset Analysis
Exploratory and structural analysis of the raw Enron email dataset (`Enron_Txt_fn_orignal.csv`).

### Objectives:
- Inspect dataset dimensions, column types, and sample records
- Check class balance between HAM (0) and SPAM (1)
- Identify missing values and null entries
- Investigate duplicate emails, filenames, and potential label conflicts
- Compute initial character and word length statistics

## 1. Load Data & Basic Structure Inspection

In [11]:
# Import pandas for data manipulation and tabular analysis
import pandas as pd

In [13]:
# Load raw email records
# Note: If running from notebooks folder, path may be '../data/raw/ENRON-spam.csv'
df = pd.read_csv("Enron_Txt_fn_orignal.csv")
print(df)

       label                                              email  \
0          0      ['Subject: christmas tree farm pictures  \n']
1          0          ['Subject: re : rankings  \nthank you .']
2          0  ['Subject: leadership development pilot  \nsal...
3          0  ["Subject: key dates and impact of upcoming sa...
4          0  ['Subject: key hr issues going forward  \na ) ...
...      ...                                                ...
33711      1  ["Subject: do you wish for a more active sex l...
33712      1  ['Subject: bloow in 5 - 10 times the time  \nl...
33713      1  ['Subject: why didnt you say hi  \nthere is th...
33714      1  ['Subject: dear sir , i am interested in it  \...
33715      1  ['Subject:   \nhtml\nbody\nb\npwhy not take a ...

                               filename
0        0001.1999-12-10.farmer.ham.txt
1      0001.1999-12-10.kaminski.ham.txt
2          0001.2000-01-17.beck.ham.txt
3         0001.2000-06-06.lokay.ham.txt
4       0001.2001-02-07.kitchen.ham.txt
...                                 ...
33711       5998.2005-09-06.GP.spam.txt
33712       5999.2005-07-30.BG.spam.txt
33713       5999.2005-09-06.GP.spam.txt
33714       6000.2005-07-31.BG.spam.txt
33715       6000.2005-09-06.GP.spam.txt

[33716 rows x 3 columns]

In [14]:
# Preview the first 5 records
df.head()

,label,email,filename
0,0,['Subject: christmas tree farm pictures \n'],0001.1999-12-10.farmer.ham.txt
1,0,['Subject: re : rankings \nthank you .'],0001.1999-12-10.kaminski.ham.txt
2,0,['Subject: leadership development pilot \nsal...,0001.2000-01-17.beck.ham.txt
3,0,"[""Subject: key dates and impact of upcoming sa...",0001.2000-06-06.lokay.ham.txt
4,0,['Subject: key hr issues going forward \na ) ...,0001.2001-02-07.kitchen.ham.txt

In [16]:
# Preview the last 5 records
df.tail()

,label,email,filename
33711,1,"[""Subject: do you wish for a more active sex l...",5998.2005-09-06.GP.spam.txt
33712,1,['Subject: bloow in 5 - 10 times the time \nl...,5999.2005-07-30.BG.spam.txt
33713,1,['Subject: why didnt you say hi \nthere is th...,5999.2005-09-06.GP.spam.txt
33714,1,"['Subject: dear sir , i am interested in it \...",6000.2005-07-31.BG.spam.txt
33715,1,['Subject: \nhtml\nbody\nb\npwhy not take a ...,6000.2005-09-06.GP.spam.txt

In [17]:
# Check total rows and columns (shape)
df.shape

(33716, 3)

In [18]:
# Inspect available column names
df.columns

Index(['label', 'email', 'filename'], dtype='object')

In [19]:
# Summary of columns, non-null counts, and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33716 entries, 0 to 33715
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   label     33716 non-null  int64
 1   email     33716 non-null  object
 2   filename  33716 non-null  object
dtypes: int64(1), object(2)
memory usage: 790.3+ KB

## 2. Class Distribution & Missing Values

In [21]:
# Count records per class (0 = HAM / Legitimate, 1 = SPAM)
df["label"].value_counts()

label
1    17171
0    16545
Name: count, dtype: int64

In [23]:
# Proportion / percentage of HAM vs SPAM
df["label"].value_counts(normalize=True)

label
1    0.509283
0    0.490717
Name: proportion, dtype: float64

In [24]:
# Check for missing/null values across columns
df.isnull().sum()

label       0
email       0
filename    0
dtype: int64

## 3. Duplicate Analysis & Investigation

In [26]:
# Count duplicate email text contents
df["email"].duplicated().sum()

np.int64(3222)

In [28]:
# Check for duplicate filenames
df["filename"].duplicated().sum()

np.int64(0)

above showed that dataset contains the duplicate emails . we need to invistigate this

In [13]:
# Total duplicate rows across all columns
df.duplicated().sum()

np.int64(0)

In [14]:
# Filter and inspect rows that share identical email text
duplicate_emails = df[df["email"].duplicated(keep=False)]

duplicate_emails.head(10)

,label,email,filename
9,0,['Subject: calpine daily gas nomination \n- c...,0003.1999-12-14.farmer.ham.txt
29,0,['Subject: human resources organization \nas ...,0009.2000-06-07.lokay.ham.txt
84,0,['Subject: global risk management operations ...,0027.2000-01-17.beck.ham.txt
150,0,['Subject: invoice processing \nas you are aw...,0048.2000-06-14.lokay.ham.txt
158,0,"[""Subject: re : global risk management operati...",0050.2000-01-18.beck.ham.txt
192,0,['Subject: travel announcement \nenron global...,0062.2000-06-14.lokay.ham.txt
205,0,['Subject: pac enrollment \nlast year the enr...,0066.2000-06-15.lokay.ham.txt
281,0,['Subject: organizational announcement \nenro...,0092.2000-01-25.beck.ham.txt
307,0,['Subject: cera says average natural gas price...,0101.2000-06-20.lokay.ham.txt
329,0,['Subject: cera says average natural gas price...,0109.2000-06-20.lokay.ham.txt

In [15]:
# View label, email, and filename for duplicate records
duplicate_emails[["label", "email", "filename"]].head(20)

,label,email,filename
9,0,['Subject: calpine daily gas nomination \n- c...,0003.1999-12-14.farmer.ham.txt
29,0,['Subject: human resources organization \nas ...,0009.2000-06-07.lokay.ham.txt
84,0,['Subject: global risk management operations ...,0027.2000-01-17.beck.ham.txt
150,0,['Subject: invoice processing \nas you are aw...,0048.2000-06-14.lokay.ham.txt
158,0,"[""Subject: re : global risk management operati...",0050.2000-01-18.beck.ham.txt
192,0,['Subject: travel announcement \nenron global...,0062.2000-06-14.lokay.ham.txt
205,0,['Subject: pac enrollment \nlast year the enr...,0066.2000-06-15.lokay.ham.txt
281,0,['Subject: organizational announcement \nenro...,0092.2000-01-25.beck.ham.txt
307,0,['Subject: cera says average natural gas price...,0101.2000-06-20.lokay.ham.txt
329,0,['Subject: cera says average natural gas price...,0109.2000-06-20.lokay.ham.txt
463,0,"[""Subject: capital book \nto further the proc...",0153.2001-04-17.williams.ham.txt
479,0,['Subject: update - reimbursement of individua...,0158.2000-06-26.lokay.ham.txt
494,0,['Subject: california energy crisis \ncalifor...,0163.2001-03-13.kitchen.ham.txt
499,0,['Subject: organization announcement \nenron ...,0165.2000-02-02.beck.ham.txt
506,0,['Subject: road - show . com q 4 i . com choos...,0167.2000-02-02.beck.ham.txt
517,0,['Subject: enron and chase manhattan bank sign...,0171.2000-02-02.beck.ham.txt
577,0,['Subject: energy operations promotions \ni a...,0192.2000-02-06.beck.ham.txt
578,0,['Subject: enronoptions - your stock option pr...,0192.2000-06-28.lokay.ham.txt
618,0,['Subject: global risk management operations ...,0208.2000-01-17.farmer.ham.txt
622,0,['Subject: entouch newsletter \nbusiness high...,0208.2001-04-21.williams.ham.txt

In [30]:
# Verify whether identical emails ever have conflicting labels (both ham and spam)
duplicate_label_check = (
    df.groupby("email")["label"]
      .nunique()
)

duplicate_label_check.value_counts()

label
1    30494
Name: count, dtype: int64

In [29]:
# Re-check class distribution counts
df["label"].value_counts()

label
1    17171
0    16545
Name: count, dtype: int64

## 4. Email Length & Repetition Statistics

In [31]:
# Compute initial character count and word count per email and view statistical summary
df["char_count"] = df["email"].str.len()
df["word_count"] = df["email"].str.split().str.len()

df[["char_count", "word_count"]].describe()

         char_count    word_count
count  33716.000000  33716.000000
mean    1418.318395    264.542413
std     2124.794170    394.717268
min       17.000000      2.000000
25%      364.000000     66.000000
50%      741.000000    141.000000
75%     1596.000000    306.000000
max    21900.000000   5367.000000

In [32]:
# Number of unique email texts
df["email"].nunique()

30494

In [21]:
# How many rows are actually repeated?
len(df) - df["email"].nunique()

3222

In [22]:
# Frequency distribution: how many times duplicate emails are repeated
duplicate_frequency = df["email"].value_counts()

duplicate_frequency.value_counts().sort_index()

count
1     27463
2      2939
3        70
4        13
5         3
6         2
7         1
8         1
20        1
51        1
Name: count, dtype: int64