In [1]:
import pandas as pd

In [8]:
Trec = pd.read_csv("../data/raw/trec_parsed_full.csv")
Enron = pd.read_csv("../data/raw/ENRON-spam.csv")
SpamAssassin = pd.read_csv("../data/raw/spamassassin_binary_dataset.csv")

In [ ]:
Trec.head()

,subject,body,label,year,orig_id,source
0,"Generic Cialis, branded quality@",NaN,1,2007.0,inmail.1,trec
1,Typo in /debian/README,"Hi, i've just updated from the gulus and I che...",0,2007.0,inmail.2,trec
2,authentic viagra,Mega authenticV I A G R A $ DISCOUNT priceC...,1,2007.0,inmail.3,trec
3,Nice talking with ya,"\nHey Billy, \n\nit was really fun going out t...",1,2007.0,inmail.4,trec
4,or trembling; stomach cramps; trouble in sleep...,"\nsystem"" of the home. It will have the capab...",1,2007.0,inmail.5,trec

In [13]:
Trec.tail()

,subject,body,label,year,orig_id,source
75414,the reply for your request for a job place [le...,NaN,1,2007.0,inmail.75415,trec
75415,the reply for your request for a job place [le...,NaN,1,2007.0,inmail.75416,trec
75416,"Re: [R] Me again, about the horrible documenta...","For those who are interested, I just cook a li...",0,2007.0,inmail.75417,trec
75417,Re: [R] RODBC problem,"Hello,\n\nas I wrote I call\n\n sqlFetch(chan...",0,2007.0,inmail.75418,trec
75418,I wanted the desk at his own laws: of the. Bu...,"Well, are implicated. When does not the stage...",1,2007.0,inmail.75419,trec

In [15]:
Trec['label'].value_counts()

label
1    50199
0    25220
Name: count, dtype: int64